# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PCE',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Persona')),
                ('porcentaje', models.FloatField()),
                ('discapacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Discapacidad')),
            ],
            bases=('usuarios.persona',),
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Persona')),
            ],
            bases=('usuarios.persona',),
        ),
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('voluntario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Voluntario')),
                ('conocimiento_priemerosaux', models.BooleanField(default=False)),
            ],
            bases=('usuarios.voluntario',),
        ),
        migrations.CreateModel(
            name='TrabajadorPublico',
            fields=[
                ('voluntario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Voluntario')),
                ('institucion', models.CharField(max_length=250)),
                ('especialidad', models.CharField(max_length=250)),
            ],
            bases=('usuarios.voluntario',),
        ),
    ]
