# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0002_auto_20160106_0850'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='dispositivo',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='push_notifications.GCMDevice'),
            preserve_default=False,
        ),
    ]
